// src/ui/icons.js
/**
 * Renders all Lucide icons found in the given scope.
 * Uses the bundled Lucide package instead of CDN.
 */

import {
  createIcons,
  ChevronUp,
  ChevronDown,
  Trash2,
  ArrowRight,
  BookmarkMinus,
  BookmarkPlus,
  CheckCircle,
  AlertCircle,
  ScrollText,
  Search,
  AlertTriangle,
  Layers,
  Eye,
  BookType,
  Sparkles,
  Archive,
  Compass,
  MoreHorizontal,
  Link,
  Download,
  FileText,
  ArrowUp,
  ArrowDown,
  TriangleAlert,
  LogOut,
  LogIn,
  X,
  Feather,
  ChevronLeft,
  ChevronRight,
  Cloud,
  Send,
  Mic,
  Plus,
  Wand2,
  BarChart2,
  Circle,
  PenTool,
  BadgeX,
  PanelLeftClose,
  PanelLeftOpen,
  LayoutGrid,
  Clock,
  Bookmark,
  Share2,
  User,
  Globe,
  Settings,
  BookOpen,
  Flame,
  Users2,
  Clock4,
  Signature,
  Scroll,
  UserCheck,
  MapPin,
  Tags,
  Target,
  Check,
  ArrowLeft,
  Settings2,
  Tag,
  Info,
  Clock3,
  Filter,
  ArrowUpDown,
  WandSparkles,
  MessageSquarePlus,
  Database,
  RotateCcw,
  Play,
  Heart,
  Home,
} from 'lucide';

/**
 * Renders all Lucide icons found in the given scope.
 * Safe to call multiple times.
 *
 * @param {ParentNode} [scope=document] - The DOM scope to search for icons
 */
export function initIcons(scope = document) {
  try {
    createIcons({
      icons: {
        ChevronUp,
        ChevronDown,
        Trash2,
        ArrowRight,
        BookmarkMinus,
        BookmarkPlus,
        CheckCircle,
        AlertCircle,
        ScrollText,
        Search,
        AlertTriangle,
        Layers,
        Eye,
        BookType,
        Sparkles,
        Archive,
        Compass,
        MoreHorizontal,
        Link,
        Download,
        FileText,
        ArrowUp,
        ArrowDown,
        TriangleAlert,
        LogOut,
        LogIn,
        X,
        Feather,
        ChevronLeft,
        ChevronRight,
        Cloud,
        Send,
        Mic,
        Plus,
        Wand2,
        BarChart2,
        Circle,
        PenTool,
        BadgeX,
        PanelLeftClose,
        PanelLeftOpen,
        LayoutGrid,
        Clock,
        Bookmark,
        Share2,
        User,
        Globe,
        Settings,
        BookOpen,
        Flame,
        Users2,
        Clock4,
        Signature,
        Scroll,
        UserCheck,
        MapPin,
        Tags,
        Target,
        Check,
        ArrowLeft,
        Settings2,
        Tag,
        Info,
        Clock3,
        Filter,
        ArrowUpDown,
        WandSparkles,
        MessageSquarePlus,
        Database,
        RotateCcw,
        Play,
        Heart,
        Home,
      },
      nameAttr: 'data-lucide',
      attrs: {
        'stroke-width': 2,
      },
    });
  } catch (err) {
    console.warn('[icons] Failed to render Lucide icons:', err);
  }
}
